#FROM ubuntu:22.04
FROM --platform=$BUILDPLATFORM ubuntu:latest

# Evita prompt interattivi durante installazione
ENV DEBIAN_FRONTEND=noninteractive

# Installa OpenSSH Server
RUN apt-get update && \
    apt-get install -y openssh-server sudo && \
    mkdir /var/run/sshd

# Aggiorna il sistema e installa i pacchetti richiesti
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        gcc g++ make nano && \
    apt-get install -y openmpi-bin libopenmpi-dev \
        python3 python3-pip python3-matplotlib python3-pandas \
        nvidia-cuda-toolkit && \   
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


WORKDIR /root

# Avvia SSH in foreground (mantiene vivo il container)
CMD ["/usr/sbin/sshd", "-D"]